version: '3.8'

services:

  knowledgebase-postgres:
    image: postgres:15.3
    restart: always
    container_name: kb_postgres_podman
    env_file:
      - .env-docker
    environment:
      PGPORT: ${DB_PORT}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg-local:/var/lib/postgresql/data
    networks:
      - my_network
    ports:
      - "8863:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h knowledgebase-postgres -U kb_rest" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  frontend:
    build:
      context: .
      dockerfile: ./docker/knowledgebase/Dockerfile
    image: kb/kb-ui
    container_name: kb_ui
    ports:
      - "4262:80"
    networks:
      - my_network
    #depends_on:
    #  - backend

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    image: kb/kb-backend
    container_name: kb_backend
    ports:
      - "3335:3000"
    env_file:
      - .env-docker
    networks:
      - my_network
    depends_on:
      knowledgebase-postgres:
        condition: service_healthy

  #pgadmin:
  #  image: dpage/pgadmin4
  #  container_name: pgadmin4
  #  ports:
  #    - "8888:80"
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: nils.hansen@yahoo.de
  #    PGADMIN_DEFAULT_PASSWORD: root


volumes:
  pg-local:
    driver: local

networks:
  my_network:
    driver: bridge
