version: '3.8'

services:

  frontend:
    build:
      context: .
      dockerfile: ./docker/knowledgebase/Dockerfile
    container_name: kb_ui
    ports:
      - "4261:80"
    networks:
      - my_network
    #depends_on:
    #  - backend

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: kb_backend
    ports:
      - "3333:3000"
    env_file:
      - .env-docker
    networks:
      - my_network
    depends_on:
      - knowledgebase-postgres

  knowledgebase-postgres:
    image: postgres:15.3
    restart: always
    #shm_size: 128mb
    container_name: kb_postgres
    environment:
      PGPORT: 5432
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: kb_rest
    volumes:
      - pg-local:/var/lib/postgresql/data
    networks:
      - my_network
    ports:
      - "8862:5432"

  #pgadmin:
  #  image: dpage/pgadmin4
  #  container_name: pgadmin4
  #  ports:
  #    - "8888:80"
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: nils.hansen@yahoo.de
  #    PGADMIN_DEFAULT_PASSWORD: root


volumes:
  pg-local:
    driver: local

networks:
  my_network:
    driver: bridge
