# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - "**"

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: npm ci
        run: npm ci
      - name: Build knowledgebase
        run: npm run kb:build:prod
      - name: Build backend
        run: npm run backend:build:prod
      - name: Build storybook
        run: npm run kb:storybook:build
      - name: Test knowledgebase
        run: npm run kb:test
